[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ExaModels = "1037b233-b668-4ce9-9b63-f9f681f55dd2"
HSL_jll = "017b0a0e-03f4-516a-9b91-836bbd1904dd"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
KNITRO = "67920dd8-b58e-52a8-8622-53c4cffbe346"
MadNCL = "434a0bcb-5a7c-42b2-a9d3-9e3f760e7af0"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
MadNLPGPU = "d72a61cc-809d-412f-99be-fd81f4b8a598"
MadNLPHSL = "7fb6135f-58fe-4112-84ca-653cf5be0c77"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsJuMP = "792afdf1-32c1-5681-94e0-d7bf7a5df49e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PowerModelsSecurityConstrained = "53333297-f92c-5019-980b-942fc744b407"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
